import random
from datetime import datetime, timedelta

PROJECTS = [
    {
        "id": "proj-001",
        "name": "Amazon Rainforest REDD+",
        "type": "Forest Conservation",
        "country": "Brazil",
        "region": "South America",
        "lat": -3.4653,
        "lng": -62.2159,
        "rating": "AAA",
        "score": 96,
        "credits_available": 245000,
        "price_per_ton": 18.50,
        "total_credits": 500000,
        "credits_retired": 180000,
        "vintage": 2024,
        "methodology": "VM0015",
        "verified_by": "Carbonix AI + Verra",
        "area_hectares": 120000,
        "co2_avoided_tons": 500000,
        "last_satellite_check": "2026-04-27T14:30:00Z",
        "satellite_status": "verified",
        "ndvi_change": 0.02,
        "deforestation_risk": "low",
        "description": "Protecting 120,000 hectares of pristine Amazon rainforest from deforestation through community-based conservation and sustainable livelihood programs.",
        "image": "amazon",
        "tags": ["REDD+", "Biodiversity", "Community"],
    },
    {
        "id": "proj-002",
        "name": "Saharan Solar Farm Complex",
        "type": "Renewable Energy",
        "country": "Morocco",
        "region": "Africa",
        "lat": 31.0,
        "lng": -5.5,
        "rating": "AA",
        "score": 89,
        "credits_available": 180000,
        "price_per_ton": 14.20,
        "total_credits": 350000,
        "credits_retired": 95000,
        "vintage": 2025,
        "methodology": "ACM0002",
        "verified_by": "Carbonix AI + Gold Standard",
        "area_hectares": 5000,
        "co2_avoided_tons": 350000,
        "last_satellite_check": "2026-04-27T09:15:00Z",
        "satellite_status": "verified",
        "ndvi_change": None,
        "deforestation_risk": None,
        "description": "A 2GW concentrated solar power installation replacing coal-fired generation across North Africa, providing clean energy to 3 million households.",
        "image": "solar",
        "tags": ["Solar", "Grid Replacement", "Clean Energy"],
    },
    {
        "id": "proj-003",
        "name": "Borneo Peatland Restoration",
        "type": "Wetland Restoration",
        "country": "Indonesia",
        "region": "Asia",
        "lat": 1.5,
        "lng": 110.0,
        "rating": "AA",
        "score": 87,
        "credits_available": 320000,
        "price_per_ton": 22.80,
        "total_credits": 600000,
        "credits_retired": 210000,
        "vintage": 2024,
        "methodology": "VM0036",
        "verified_by": "Carbonix AI",
        "area_hectares": 85000,
        "co2_avoided_tons": 600000,
        "last_satellite_check": "2026-04-26T22:00:00Z",
        "satellite_status": "verified",
        "ndvi_change": 0.05,
        "deforestation_risk": "medium",
        "description": "Re-wetting and restoring degraded peatlands in Borneo, preventing massive carbon emissions from peat decomposition and fires.",
        "image": "peatland",
        "tags": ["Peatland", "Restoration", "Fire Prevention"],
    },
    {
        "id": "proj-004",
        "name": "Kenyan Biochar Initiative",
        "type": "Carbon Removal",
        "country": "Kenya",
        "region": "Africa",
        "lat": -0.0236,
        "lng": 37.9062,
        "rating": "A",
        "score": 82,
        "credits_available": 45000,
        "price_per_ton": 85.00,
        "total_credits": 75000,
        "credits_retired": 22000,
        "vintage": 2025,
        "methodology": "Puro.earth",
        "verified_by": "Carbonix AI + Puro.earth",
        "area_hectares": 2000,
        "co2_avoided_tons": 75000,
        "last_satellite_check": "2026-04-27T11:45:00Z",
        "satellite_status": "verified",
        "ndvi_change": 0.08,
        "deforestation_risk": None,
        "description": "Converting agricultural waste into stable biochar, sequestering carbon for 1000+ years while improving soil fertility for smallholder farmers.",
        "image": "biochar",
        "tags": ["Biochar", "CDR", "Agriculture"],
    },
    {
        "id": "proj-005",
        "name": "Norwegian Direct Air Capture",
        "type": "Carbon Removal",
        "country": "Norway",
        "region": "Europe",
        "lat": 60.472,
        "lng": 8.4689,
        "rating": "AAA",
        "score": 98,
        "credits_available": 8000,
        "price_per_ton": 420.00,
        "total_credits": 15000,
        "credits_retired": 5200,
        "vintage": 2026,
        "methodology": "Puro.earth",
        "verified_by": "Carbonix AI + Puro.earth",
        "area_hectares": 50,
        "co2_avoided_tons": 15000,
        "last_satellite_check": "2026-04-27T16:00:00Z",
        "satellite_status": "verified",
        "ndvi_change": None,
        "deforestation_risk": None,
        "description": "Industrial-scale direct air capture facility powered by 100% renewable hydroelectric energy, with permanent geological storage in basalt formations.",
        "image": "dac",
        "tags": ["DAC", "CDR", "Permanent Storage"],
    },
    {
        "id": "proj-006",
        "name": "Indian Mangrove Restoration",
        "type": "Blue Carbon",
        "country": "India",
        "region": "Asia",
        "lat": 21.9497,
        "lng": 88.8996,
        "rating": "A",
        "score": 79,
        "credits_available": 95000,
        "price_per_ton": 16.50,
        "total_credits": 200000,
        "credits_retired": 67000,
        "vintage": 2024,
        "methodology": "VM0033",
        "verified_by": "Carbonix AI + Verra",
        "area_hectares": 15000,
        "co2_avoided_tons": 200000,
        "last_satellite_check": "2026-04-27T07:30:00Z",
        "satellite_status": "flagged",
        "ndvi_change": -0.03,
        "deforestation_risk": "high",
        "description": "Restoring degraded mangrove ecosystems in the Sundarbans, providing coastal protection, biodiversity habitat, and blue carbon sequestration.",
        "image": "mangrove",
        "tags": ["Blue Carbon", "Mangroves", "Coastal"],
    },
    {
        "id": "proj-007",
        "name": "Chilean Wind Farm Cluster",
        "type": "Renewable Energy",
        "country": "Chile",
        "region": "South America",
        "lat": -27.3668,
        "lng": -70.3323,
        "rating": "AA",
        "score": 91,
        "credits_available": 210000,
        "price_per_ton": 11.30,
        "total_credits": 400000,
        "credits_retired": 145000,
        "vintage": 2025,
        "methodology": "ACM0002",
        "verified_by": "Carbonix AI + Gold Standard",
        "area_hectares": 8000,
        "co2_avoided_tons": 400000,
        "last_satellite_check": "2026-04-27T13:00:00Z",
        "satellite_status": "verified",
        "ndvi_change": None,
        "deforestation_risk": None,
        "description": "A cluster of 150 offshore and onshore wind turbines in the Atacama region, displacing fossil fuel generation across Chile's national grid.",
        "image": "wind",
        "tags": ["Wind", "Grid Replacement", "Clean Energy"],
    },
    {
        "id": "proj-008",
        "name": "Congo Basin Forest Protection",
        "type": "Forest Conservation",
        "country": "DR Congo",
        "region": "Africa",
        "lat": -0.228,
        "lng": 25.9231,
        "rating": "B",
        "score": 65,
        "credits_available": 400000,
        "price_per_ton": 6.80,
        "total_credits": 800000,
        "credits_retired": 120000,
        "vintage": 2023,
        "methodology": "VM0009",
        "verified_by": "Carbonix AI",
        "area_hectares": 250000,
        "co2_avoided_tons": 800000,
        "last_satellite_check": "2026-04-25T20:00:00Z",
        "satellite_status": "under_review",
        "ndvi_change": -0.07,
        "deforestation_risk": "high",
        "description": "Large-scale avoided deforestation project in the Congo Basin. Currently under enhanced review due to detected land cover changes.",
        "image": "congo",
        "tags": ["REDD+", "Under Review", "High Risk"],
    },
]

PORTFOLIO = [
    {"project_id": "proj-001", "tons_held": 12000, "avg_price": 16.20, "purchased": "2025-11-15"},
    {"project_id": "proj-005", "tons_held": 500, "avg_price": 380.00, "purchased": "2026-01-22"},
    {"project_id": "proj-003", "tons_held": 8000, "avg_price": 20.50, "purchased": "2025-09-03"},
    {"project_id": "proj-007", "tons_held": 15000, "avg_price": 10.80, "purchased": "2026-02-10"},
    {"project_id": "proj-004", "tons_held": 2000, "avg_price": 78.00, "purchased": "2026-03-18"},
]

def _random_transactions(n=50):
    txns = []
    buyers = [
        "Microsoft Corp", "Shell PLC", "Delta Airlines", "Shopify Inc",
        "Stripe Inc", "Goldman Sachs", "Maersk A/S", "Unilever PLC",
        "Swiss Re", "Salesforce Inc", "JP Morgan", "HSBC Holdings",
        "BMW Group", "Nestle SA", "Amazon.com",
    ]
    for i in range(n):
        proj = random.choice(PROJECTS)
        tons = random.randint(100, 20000)
        price = proj["price_per_ton"] * random.uniform(0.9, 1.1)
        txns.append({
            "id": f"tx-{1000+i}",
            "buyer": random.choice(buyers),
            "project_id": proj["id"],
            "project_name": proj["name"],
            "tons": tons,
            "price_per_ton": round(price, 2),
            "total_value": round(tons * price, 2),
            "timestamp": (datetime.now() - timedelta(hours=random.randint(1, 720))).isoformat(),
            "status": random.choices(["completed", "pending", "verified"], weights=[70, 15, 15])[0],
            "rating": proj["rating"],
        })
    txns.sort(key=lambda x: x["timestamp"], reverse=True)
    return txns

TRANSACTIONS = _random_transactions(50)

MARKET_STATS = {
    "total_volume_30d": sum(t["total_value"] for t in TRANSACTIONS),
    "total_tons_30d": sum(t["tons"] for t in TRANSACTIONS),
    "avg_price": round(sum(t["price_per_ton"] for t in TRANSACTIONS) / len(TRANSACTIONS), 2),
    "active_projects": len(PROJECTS),
    "verified_projects": sum(1 for p in PROJECTS if p["satellite_status"] == "verified"),
    "flagged_projects": sum(1 for p in PROJECTS if p["satellite_status"] in ("flagged", "under_review")),
    "total_credits_available": sum(p["credits_available"] for p in PROJECTS),
    "total_credits_retired": sum(p["credits_retired"] for p in PROJECTS),
}

PRICE_HISTORY = []
base_prices = {"Forest Conservation": 12, "Renewable Energy": 9, "Wetland Restoration": 18, "Carbon Removal": 120, "Blue Carbon": 13}
for i in range(365):
    d = (datetime.now() - timedelta(days=364 - i)).strftime("%Y-%m-%d")
    for ptype, base in base_prices.items():
        drift = base * (1 + 0.15 * (i / 365)) + random.uniform(-base * 0.05, base * 0.05)
        PRICE_HISTORY.append({"date": d, "type": ptype, "price": round(drift, 2)})
